name: Build

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain:1-bookworm-slim-node22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run ci:gha
      - name: Run Package
        run: npm run jsii:pacmak:parallel
